language: rust
cache: cargo
matrix:
  include:
    - rust: stable
      before_script:
        - rustup component add rustfmt-preview
        - rustup component add clippy-preview
      script:
        - |
          cargo fmt -- --check &&
          cargo build &&
          cargo clippy -- -D clippy

    - rust: stable
      env: GFX_MASTER=true
      script:
        - ./ci/build-gfx-master
  allow_failures:
    - env: GFX_MASTER=true
