[package]
name = "gfx-hal-tutorials"
version = "0.1.0"
authors = ["***Realname*** ***Lastname*** <***redacted.email@redacted.nope***>"]

[dependencies]
winit = "=0.16.2"

[dependencies.gfx-hal]
git = "https://github.com/gfx-rs/gfx"
rev = "e5df0879"

[dependencies.gfx-backend-metal]
git = "https://github.com/gfx-rs/gfx"
rev = "e5df0879"

[build-dependencies]
glsl-to-spirv = "=0.1.5"
